version: "3.9"

services:
  energy_db:
    image: postgres:15
    container_name: energy_db
    restart: always
    environment:
      POSTGRES_DB: energy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - energy_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d energy"]
      interval: 5s
      timeout: 5s
      retries: 10

  dash_app:
    build: ./dash_app
    container_name: energy_dash
    restart: always
    env_file:
      - .env
    depends_on:
      energy_db:
        condition: service_healthy
    ports:
      - "8050:8050"

  importer_weather:
    build: ./importer_weather
    container_name: importer_weather
    restart: always
    env_file:
      - .env
    depends_on:
      energy_db:
        condition: service_healthy

  importer_price:
    build: ./importer_price
    container_name: importer_price
    restart: always
    env_file:
      - .env
    depends_on:
      energy_db:
        condition: service_healthy

  importer_entsoe:
    build: ./importer_entsoe
    container_name: importer_entsoe
    restart: always
    env_file:
      - .env
    depends_on:
      energy_db:
        condition: service_healthy

  importer_solar_elering:
    build: ./importer_solar_elering
    container_name: importer_solar_elering
    restart: always
    env_file:
      - .env
    depends_on:
      energy_db:
        condition: service_healthy

  importer_solar_eu:
    build: ./importer_solar_eu
    container_name: importer_solar_eu
    restart: always
    env_file:
      - .env
    depends_on:
      energy_db:
        condition: service_healthy

  importer_solar_radiation:
    build: ./importer_solar_radiation
    container_name: importer_solar_radiation
    restart: always
    env_file:
      - .env
    depends_on:
      energy_db:
        condition: service_healthy

volumes:
  energy_data: